#!/usr/bin/env bash
# gen_epoch_manifest.sh — build the epoch laboratory for the pinned Reference
# (plan §18 epoch lab; bead fln-euo). Immutable once published: regeneration must
# byte-match, and any discovery lands as a reviewed, hashed revision.
#
# Records, deterministically (no timestamps, no absolute paths):
#   * the SUITE.lock reference pin and the verified binary identity;
#   * a hashed inventory of the pinned toolchain's executables;
#   * the environment-normalization recipe differential rigs must use;
#   * exact reproduction commands;
#   * the C1 corpus slice: deterministic selection from the vendored upstream test
#     suite with per-file sha256 and the directory-derived expected outcome class,
#     plus a recorded-transcript baseline (observed binary behavior, oracle
#     authority rank 2) and a quirk ledger for files whose plain-invocation
#     behavior departs from the directory expectation.
#
# Usage: scripts/tribunal/gen_epoch_manifest.sh [--check]
#   --check  regenerate to scratch and diff against the published lab (CI drift
#            mode; exit 1 on drift, 2 on setup failure)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MODE="${1:-generate}"
C1_SIZE=10

note() { echo "[epoch_manifest] $*" >&2; }

# ---- pinned binary, verified against SUITE.lock (same law as gen_core_fixtures) --------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"
TOOLCHAIN_DIR="$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG"
LEAN="$TOOLCHAIN_DIR/bin/lean"
if [ ! -x "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi
VERSION="$("$LEAN" --version)"
if ! grep -q "$PIN_COMMIT" <<<"$VERSION"; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  exit 2
fi

EPOCH_DIR="$ROOT/tribunal/epochs/$PIN_TAG"
CORPUS_DIR="$ROOT/vendor/lean4-src/tests/elab"
DIAG_CORPUS_REL="vendor/lean4-src/tests/elab_fail"
D1_SIZE=6

# The normalization recipe every rig applies before invoking the oracle.
oracle_env() { # oracle_env <cmd...>
  env -u LEAN_PATH -u LEAN_SYSROOT LC_ALL=C TZ=UTC "$@"
}

# Deterministic C1 slice: the $C1_SIZE smallest upstream elab tests by (bytes, name),
# restricted to self-contained files (no #exit/#eval-of-IO front matter surprises are
# fine — behavior is recorded, not assumed).
select_slice() {
  find "$CORPUS_DIR" -maxdepth 1 -name '*.lean' -printf '%s %f\n' \
    | sort -n -k1,1 -k2,2 \
    | awk -v n="$C1_SIZE" 'NR <= n { print $2 }'
}

# D1: the smallest upstream elab_fail tests — real Reference DIAGNOSTIC transcripts,
# the golden corpus the faithful renderer (fln-core::diag) is proven against.
select_diag_slice() {
  find "$ROOT/$DIAG_CORPUS_REL" -maxdepth 1 -name '*.lean' -printf '%s %f\n' \
    | sort -n -k1,1 -k2,2 \
    | awk -v n="$D1_SIZE" 'NR <= n { print $2 }'
}

emit_manifest() { # emit_manifest <dest-dir>
  local dest="$1"
  mkdir -p "$dest/transcripts"
  {
    printf '# MANIFEST.txt — epoch laboratory for the pinned Reference (bead fln-euo).\n'
    printf '# GENERATED by scripts/tribunal/gen_epoch_manifest.sh; never edit by hand.\n'
    printf '# Immutable once published: revisions are reviewed, hashed regenerations.\n'
    printf 'schema fln-epoch-manifest/1\n'
    printf 'reference leanprover/lean4 tag=%s commit=%s\n' "$PIN_TAG" "$PIN_COMMIT"
    printf 'binary-version %s\n' "$VERSION"
    printf '\n# ---- toolchain executable inventory (sha256, bytes) ----\n'
    for exe in "$TOOLCHAIN_DIR"/bin/*; do
      [ -f "$exe" ] || continue
      printf 'executable %s sha256=%s bytes=%s\n' \
        "$(basename "$exe")" \
        "$(sha256sum "$exe" | cut -d' ' -f1)" \
        "$(stat -c %s "$exe")"
    done
    printf '\n# ---- environment-normalization recipe (applied by every rig) ----\n'
    printf 'env-unset LEAN_PATH\n'
    printf 'env-unset LEAN_SYSROOT\n'
    printf 'env-set LC_ALL=C\n'
    printf 'env-set TZ=UTC\n'
    printf '\n# ---- reproduction commands ----\n'
    printf 'repro-manifest scripts/tribunal/gen_epoch_manifest.sh --check\n'
    printf 'repro-differential scripts/tribunal/ref_vs_ref.sh\n'
    printf '\n# ---- C1 corpus slice (deterministic: %s smallest upstream elab tests) ----\n' "$C1_SIZE"
    local file path sha expect actual_exit class
    while IFS= read -r file; do
      path="$CORPUS_DIR/$file"
      sha="$(sha256sum "$path" | cut -d' ' -f1)"
      expect="accept" # tests/elab: the upstream suite expects elaboration to succeed
      set +e
      oracle_env "$LEAN" "$path" > "$dest/transcripts/$file.stdout" 2> "$dest/transcripts/$file.stderr"
      actual_exit=$?
      set -e
      printf 'exit %s\n' "$actual_exit" > "$dest/transcripts/$file.exit"
      if [ "$actual_exit" -eq 0 ]; then class="accept"; else class="reject"; fi
      if [ "$class" = "$expect" ]; then
        printf 'c1 %s sha256=%s expect=%s observed=%s\n' "$file" "$sha" "$expect" "$class"
      else
        # Plain invocation departs from the upstream-harness expectation: a quirk
        # row, never a silent drop and never a fake pass.
        printf 'c1-quirk %s sha256=%s expect=%s observed=%s note=plain-invocation-differs-from-upstream-harness\n' \
          "$file" "$sha" "$expect" "$class"
      fi
    done < <(select_slice)
    printf '\n# ---- D1 diagnostic corpus (%s smallest upstream elab_fail tests) ----\n' "$D1_SIZE"
    printf '# Invoked with repo-relative paths so transcripts are host-independent;\n'
    printf '# the faithful renderer goldens (fln-conformance tests/diag_render.rs) replay these.\n'
    while IFS= read -r file; do
      path="$DIAG_CORPUS_REL/$file"
      sha="$(sha256sum "$ROOT/$path" | cut -d' ' -f1)"
      set +e
      ( cd "$ROOT" && oracle_env "$LEAN" "$path" ) \
        > "$dest/transcripts/$file.stdout" 2> "$dest/transcripts/$file.stderr"
      actual_exit=$?
      set -e
      printf 'exit %s\n' "$actual_exit" > "$dest/transcripts/$file.exit"
      if [ "$actual_exit" -ne 0 ]; then class="reject"; else class="accept"; fi
      if [ "$class" = "reject" ]; then
        printf 'd1 %s sha256=%s expect=reject observed=%s\n' "$file" "$sha" "$class"
      else
        printf 'd1-quirk %s sha256=%s expect=reject observed=%s note=plain-invocation-differs-from-upstream-harness\n' \
          "$file" "$sha" "$class"
      fi
    done < <(select_diag_slice)
  } > "$dest/MANIFEST.txt"
}

case "$MODE" in
  generate)
    mkdir -p "$EPOCH_DIR"
    emit_manifest "$EPOCH_DIR"
    note "oracle: $VERSION"
    note "published epoch lab at ${EPOCH_DIR#"$ROOT"/} ($(grep -c '^c1' "$EPOCH_DIR/MANIFEST.txt") corpus rows)"
    ;;
  --check)
    SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/epoch-lab-XXXXXX")"
    emit_manifest "$SCRATCH"
    rc=0
    diff -u "$EPOCH_DIR/MANIFEST.txt" "$SCRATCH/MANIFEST.txt" >&2 || rc=1
    diff -ur "$EPOCH_DIR/transcripts" "$SCRATCH/transcripts" >&2 || rc=1
    if [ "$rc" -ne 0 ]; then
      note "DRIFT: the published epoch lab does not match regeneration"
      exit 1
    fi
    note "no drift: the epoch lab is stable"
    ;;
  *)
    note "unknown mode: $MODE"
    exit 2
    ;;
esac
