#!/usr/bin/env bash
# gen_extern_census.sh — regenerate the extern census + builtin-census totality
# baseline from a pin-verified environment walk (bead franken_lean-53v; plan
# Appendix C; Rule D5/D8-2: derived, never remembered).
#
# The Reference participates here in exactly one legal capacity: census mine via
# a checked-in extraction script. The binary is located via elan, its commit is
# verified against SUITE.lock, and the output is deterministic (rows sorted, no
# timestamps, no paths) so two runs are byte-identical.
# Output: contracts/extern_census.tsv
#
# Usage: scripts/extract/gen_extern_census.sh [--check]
#   --check  regenerate to a scratch file and diff against the checked-in census
#            (CI drift mode; exit 1 on drift, 2 on setup failure)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$ROOT/scripts/extract/gen_extern_census.lean"
CENSUS="$ROOT/contracts/extern_census.tsv"
MODE="${1:-generate}"

note() { echo "[gen_extern_census] $*" >&2; }

# ---- locate and verify the pinned Reference binary (D8: oracle-only) -------------------
PIN_LINE="$(grep -E '^reference ' "$ROOT/SUITE.lock")"
PIN_TAG="$(sed -E 's/.*tag=([^ ]+).*/\1/' <<<"$PIN_LINE")"
PIN_COMMIT="$(sed -E 's/.*commit=([0-9a-f]{40}).*/\1/' <<<"$PIN_LINE")"

LEAN=""
for candidate in "$HOME/.elan/toolchains/leanprover--lean4---$PIN_TAG/bin/lean" \
                 "$(command -v lean 2>/dev/null || true)"; do
  [ -n "$candidate" ] && [ -x "$candidate" ] && { LEAN="$candidate"; break; }
done
if [ -z "$LEAN" ]; then
  note "setup failure: no Reference binary for $PIN_TAG (install: elan toolchain install leanprover/lean4:$PIN_TAG)"
  exit 2
fi

VERSION="$("$LEAN" --version)"
if ! grep -q "$PIN_COMMIT" <<<"$VERSION"; then
  note "setup failure: binary commit does not match SUITE.lock pin"
  note "  binary : $VERSION"
  note "  pinned : $PIN_TAG @ $PIN_COMMIT"
  exit 2
fi
note "oracle: $VERSION"

# ---- generate --------------------------------------------------------------------------
emit() { # emit <dest>
  {
    printf '# extern_census.tsv — GENERATED by scripts/extract/gen_extern_census.sh.\n'
    printf '# Oracle: leanprover/lean4 %s commit %s (verified against SUITE.lock).\n' "$PIN_TAG" "$PIN_COMMIT"
    printf '# Pin-verified environment walk over the full `Lean` import closure\n'
    printf '# (plan Appendix C). Regenerate with the script; never edit by hand (Rule D5).\n'
    printf 'schema fln-extern-census/1\n'
    "$LEAN" --run "$GENERATOR"
  } > "$1"
}

case "$MODE" in
  generate)
    mkdir -p "$(dirname "$CENSUS")"
    emit "$CENSUS"
    note "wrote $(grep -c $'^extern\t' "$CENSUS") extern rows, $(grep -c $'^summary\t' "$CENSUS") summary rows to ${CENSUS#"$ROOT"/}"
    ;;
  --check)
    SCRATCH="$(mktemp "${TMPDIR:-/tmp}/extern_census.XXXXXX.tsv")"
    emit "$SCRATCH"
    if ! diff -u "$CENSUS" "$SCRATCH" >&2; then
      note "DRIFT: checked-in census does not match the pin (see diff above)"
      exit 1
    fi
    note "no drift: census matches the pin"
    ;;
  *)
    note "unknown mode: $MODE"
    exit 2
    ;;
esac
