#!/usr/bin/env python3
"""gen_bignum_vectors.py — golden vectors for fln-bignum (bead franken_lean-npl).

Python's arbitrary-precision integers are the ground truth; the LEAN-SPECIFIC
semantics are encoded here exactly as KERNEL_CONTRACT.md KR-313 and the pin define
them for `Nat`:

  * sub is truncated:            a - b = max(a - b, 0)
  * division by zero is total:   a / 0 = 0
  * modulo by zero is total:     a % 0 = a
  * beq/ble return booleans (encoded 1/0)
  * shifts are plain floor ops:  a << b, a >> b

Deterministic (fixed operand table, no randomness); regenerate-and-diff is the
drift gate. Output: crates/fln-bignum/fixtures/nat_vectors.txt with rows

    op|a|b|result        (decimal; unary ops leave b empty)

Usage: gen_bignum_vectors.py [--check]
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
FIXTURE = ROOT / "crates" / "fln-bignum" / "fixtures" / "nat_vectors.txt"

# Deterministic operand table: boundary values, limb-boundary values, and large
# pseudo-structured operands (digits of pi/e truncated — fixed, not random).
OPERANDS = [
    0,
    1,
    2,
    3,
    9,
    10,
    63,
    64,
    65,
    255,
    256,
    2**32 - 1,
    2**32,
    2**64 - 1,
    2**64,
    2**64 + 1,
    2**128 - 1,
    2**128 + 5,
    2**192 + 12345,
    2**255,
    31415926535897932384626433832795028841971693993751058209749445923078164062862,
    27182818284590452353602874713526624977572470936999595749669676277240766303535,
]

SHIFT_AMOUNTS = [0, 1, 7, 63, 64, 65, 128, 200]


def rows():
    out = []

    def emit(op, a, b, result):
        out.append(f"{op}|{a}|{'' if b is None else b}|{result}")

    for a in OPERANDS:
        for b in OPERANDS:
            emit("add", a, b, a + b)
            emit("sub", a, b, max(a - b, 0))
            emit("mul", a, b, a * b)
            emit("div", a, b, 0 if b == 0 else a // b)
            emit("mod", a, b, a if b == 0 else a % b)
            emit("gcd", a, b, __import__("math").gcd(a, b))
            emit("beq", a, b, 1 if a == b else 0)
            emit("ble", a, b, 1 if a <= b else 0)
            emit("land", a, b, a & b)
            emit("lor", a, b, a | b)
            emit("lxor", a, b, a ^ b)
        for s in SHIFT_AMOUNTS:
            emit("shl", a, s, a << s)
            emit("shr", a, s, a >> s)
    # pow: small exponents only (the kernel caps exponents anyway, KR-313).
    for a in [0, 1, 2, 3, 10, 2**32, 2**64 - 1]:
        for e in [0, 1, 2, 3, 7, 16, 31]:
            emit("pow", a, e, a**e)
    return out


def render() -> str:
    body = "\n".join(rows())
    return (
        "# nat_vectors.txt — GENERATED by scripts/extract/gen_bignum_vectors.py.\n"
        "# Ground truth: CPython arbitrary-precision integers with the Lean Nat\n"
        "# semantics encoded in the generator (sub-saturation, div/mod-by-zero laws).\n"
        "# Regenerate with the script; never edit by hand (Rule D5 discipline).\n"
        "schema fln-bignum-vectors/1\n" + body + "\n"
    )


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        current = FIXTURE.read_text() if FIXTURE.exists() else ""
        if current != text:
            sys.stderr.write("[gen_bignum_vectors] DRIFT: fixture does not match generator\n")
            return 1
        sys.stderr.write("[gen_bignum_vectors] no drift\n")
        return 0
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(text)
    count = len(rows())
    sys.stderr.write(f"[gen_bignum_vectors] wrote {count} vectors to {FIXTURE.relative_to(ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
